name: Release Discord Notification

on:
  release:
    types:
      - published

jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Send release to Discord
        uses: SethCohen/github-releases-to-discord@v1
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          color: "2105893"
          username: "OpenChamber Releases"
          footer_title: "OpenChamber Changelog"
          reduce_headings: true
